//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steller.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StellerAcunMedyaDbEntities : DbContext
    {
        public StellerAcunMedyaDbEntities()
            : base("name=StellerAcunMedyaDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Testimonial> Testimonials { get; set; }
        public virtual DbSet<TblMsj> TblMsj { get; set; }
        public virtual DbSet<TblProject> TblProject { get; set; }
        public virtual DbSet<TblService> TblService { get; set; }
        public virtual DbSet<TblSkiil> TblSkiil { get; set; }
        public virtual DbSet<TblContat> TblContat { get; set; }
        public virtual DbSet<TblSocial> TblSocial { get; set; }
    }
}
