//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talha
    {
        public int AboutId { get; set; }
        public string Description { get; set; }
        public string Name_Surname { get; set; }
        public string ImageUrl { get; set; }
        public string Title { get; set; }
    }
}
