//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeature
    {
        public int featuredID { get; set; }
        public string NameSurname { get; set; }
        public string job { get; set; }
        public string Title { get; set; }
        public string image { get; set; }
        public string CVdowlondurl { get; set; }
    }
}
