//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblService
    {
        public int servicID { get; set; }
        public string servicedName { get; set; }
        public string serviceliconUrl { get; set; }
        public Nullable<bool> ServicesStatus { get; set; }
    }
}
